OGM-1390 Update JpaStandaloneNoOGMTest
  This change in behavior is due to the changes in HibernatePersistenceProvider.createEntityManagerFactory.

  Per JPA specification this method doesn't have to throw exceptions.
  Meaning that it will return null instead of throw the following exception:

  org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

  Even if the new message is different, it's still better than the old one and give
  information about what's missing in the persistence.xml