OGM-1390 Patch wildfly for integration tests to support JPA 2.2
  New annotations have been introduced and you have this error
  at start-up if you don't patch WildFly:

  Caused by: java.lang.NoClassDefFoundError: javax/persistence/TableGenerators